### ISSUE TITLE
Create unified download page for Pi4J binaries and OS images

### ISSUE THREAD

**Issue by ppmathis** [Pi4J/pi4j-os#13]
Pi4J OS can currently be downloaded at https://pi4j-download.com/, sponsored by Karakun.
In addition to that, there also exits https://pi4j.com/download/, hosted by GitHub Pages.

The following idea exists to unify these two pages:
- [x] Update GitHub Actions workflow on [Pi4J/download](https://github.com/Pi4J/download) to automatically generate a markdown file which contains (a) all files in the `download` repository and (b) all files on the `pi4j-download.com` host using external links.
- [x] Deprecate the current download page hosted on Karakun and auto-redirect to the Pi4J page
- [x] Ensure `download` repo is updated whenever either `pi4j-os` or the `download` repo contents change
- [x] Update [CrowPi documentation](https://github.com/FHNW-IP5-IP6/CrowPiGoesJavaTutorial) to reflect new way of downloading things

**Comment by savageautomate** [comment]
> Update GitHub Actions workflow on Pi4J/download to automatically generate a markdown file which contains (a) all files in the download repository and (b) all files on the pi4j-download.com host using external links.

I like this idea.  Actually its what I originally intended to do with the Pi4J downloads but never got around to it.  Some auto-generated markdown page that promoted the latest RELEASE and SNAPSHOT downloads as well as a lower complete listing of all available downloads.

Please be aware that there is an existing GitHub action for this repository that generates the necessary APT repository artifacts/metadata used by the Debian installer scripts anytime a new *.deb file is added in the repo.

**Comment by ppmathis** [comment]
This is being implemented as part of https://github.com/Pi4J/download/pull/1
The CrowPi documentation has already been updated to refer to the new download URLs

**Comment by ppmathis** [comment]
This has been fully implemented and https://pi4j.com/download/ always shows the most recent versions available for download.
