### ISSUE TITLE
Upgrade JavaFX

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-os#16]
ToDo

JavaFX 18 and a new version of DRM-library have been released.

There are two remaining issues 

- mouse pointer is not visible in DRM
- audio is not supported in JavaFX 17 build 17

In close collaboration with Gluon: upgrade to proper JavaFX (maybe JavaFX 18 ea)

Done

- [ ] JavaFX 18 is used and all examples are running
- [x] dropSound and background music of HelloFX are working
- [ ] mouse pointer is visible in HelloFX in DRM and X11-Mode
- [ ] mouse pointer can be disabled in DRM

**Comment by FDelporte** [comment]
Seems the current JavaFX version is `20.0.2`. Can this ticket be closed?

**Comment by DieterHolz** [comment]
Yes, can be closed.

The main reason is that Gluon stopped working on DRM, though. 

Maybe we can open another issue for "remove all references to DRM"
