### ISSUE TITLE
Upload images to new destination

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-os#3]
**todo**
- find new destination
  - Karakun is one of the candidates 
  - maybe something from [https://free-for.dev/#/](url)
- update github actions  

**done**
- [x] all images are deployed to new destination and can be downloaded from there
- [ ] all links in documentation to the images are updated, mainly [https://github.com/FHNW-IP5-IP6/CrowPiGoesJavaTutorial](url)

**Comment by ppmathis** [comment]
Superseded by https://github.com/Pi4J/pi4j-os/issues/13
