### ISSUE TITLE
Upgrade RaspiOS

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-os#39]
Title says it all

**Comment by FDelporte** [comment]
Seems there is a new reason to upgrade:
https://www.raspberrypi.com/news/a-new-release-of-raspberry-pi-os/

**Comment by DieterHolz** [comment]
I tried to update our  "Pi4J-Images" for Pi5. But I failed. Together with Robert we have a bash-script that does all the necessary installation. You have to install the orginal RaspiOS and start the script to get a "Pi4J environment". But there is no ready made Linux-Image.

Maybe someone with more Linux-experience can upgrade the Pi4J-images, but I'm not the right person for this task (I really tried already)

Maybe we should make the "bash-script-approach" public on the Pi4J website (but that's another task)

I would close this issue

**Comment by FDelporte** [comment]
The bash script from @eitch is on the site: https://www.pi4j.com/pi4j-os/

Should we consider the Pi4J OS project as being not supported anymore? Meaning, stick to the current version of Pi4J OS, or use latest Raspberry Pi OS + the script?

**Comment by DieterHolz** [comment]
Pi4J OS is bound to the old RaspiOS and therefore can't be used on Pi5. For me that means that we can't support this project any more. Don't you have Linux-wizards at Azul?

At FHNW we use an updated version of "the script":

https://gitlab.fhnw.ch/ip_12_preparation/hellopi5/-/blob/15daf81a8ccaa00feeba9e0884e0e6d06afffcc7/src/assembly/setup.sh
