### ISSUE TITLE
Remove 'image' from 'CrowPi Goes Java'-Project

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-os#4]
todo
- remove everything dealing with image creation from [CrowPi Goes Java](https://github.com/Pi4J/pi4j-example-crowpi)
- update [tutorial](https://github.com/FHNW-IP5-IP6/CrowPiGoesJavaTutorial)

done 
- [CrowPi Goes Java](https://github.com/Pi4J/pi4j-example-crowpi)
  - [x] successful build
  - [x] new release
- [tutorial](https://github.com/FHNW-IP5-IP6/CrowPiGoesJavaTutorial)
  - [x] developer has used the updated tutorial to start with a new CrowPi-project
  - [x] new release

**Comment by ppmathis** [comment]
> @ppmathis Do we really want to have a new release?

While I am not sure if there is any need for a new release, it could be created via GitHub UI:

- Click on **Releases** on the right hand side of the repo view
- Click on **Draft a new release** in the top right
- Specify a new tag name like `1.1.0` according to semantic versioniong
- Add some title/text and click **Publish release**

Unlike the OS images it is not such a big deal with the example/docs repos, but releases would allow to clearly mark some version as "good-to-go", so once everything has been updated it might make sense to create one.
