### ISSUE TITLE
Download link for Pi4J-Basis-OS in README.md fails

### ISSUE THREAD

**Issue by metacodez** [Pi4J/pi4j-os#41]
Unfortunately the download link for Pi4J-Basis-OS mentioned in the `README.md` does not work. Currently it points to https://pi4j-download.com/latest.php?flavor=basic which results in "Invalid image flavor specified, unable to download...". Which link do I have to use for downloading Pi4J-Basis?

**Comment by DieterHolz** [comment]
We are in preparation of the new release and not everything is ready, yet. Sorry for that.

The newest images can be downloaded from here:

https://github.com/Pi4J/pi4j-os/actions/runs/5390384409

Please be sure to add a new user 'pi', password 'pi4j' when using Raspberry Pi Imager.

**Comment by DieterHolz** [comment]
Und vielen Dank für das Interesse an den Pi4J Images.

**Comment by metacodez** [comment]
Super, vielen Dank für die schnelle Antwort die Images! Das Basic-Image werde ich gleich herunterladen!
