### ISSUE TITLE
java-kiosk improvements

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-os#6]
toDo
- create a new script `java-X11` to start a JavaFX app in X11
- log the complete submitted Java command line in both scripts
- create two new scripts `java-last-kiosk` and `java-last-X11`  that starts the last JavaFX app started by one of our starter scripts

done
- [x] `java-X11` can be used in a run-configuration in IntelliJ to start/stop the app. 
- [x] you use the Java command line from log to start the app
- you can use `java-last-kiosk` and `java-last-X11` to restart the last JavaFX app in DRM
  - [ ] from a IntelliJ run-configuration
  - [ ] at startup-time of RaspPi
  - [x] via ssh

**Comment by FDelporte** [comment]
Closing as won't do
