### ISSUE TITLE
autodetect correct value of egl.displayid

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-os#8]
todo

In java-kiosk you have to provide `egl.displayid` which is `/dev/dri/card0` or `/dev/dri/card1`. 

On Pi4 the correct value doesn't seem to be deterministic. Currently you just have to try which one is correct.

Develop an  additional script to determine which value is correct 

done

- [ ] java-kiosk will start the app without setting  `egl.displayid` from the outside or by editing the script.

**Comment by ppmathis** [comment]
Implemented as part of https://github.com/Pi4J/pi4j-os/commit/f9fce166efe0f6a625035d9aa9cc8d50778ad275

Helper binary `detect-primary-card` gets compiled during image build and will be used to auto-detect the correct card.
If auto-detection fails, `java-kiosk` refuses to start and requests the user to manually specify `egl.displayid`.
All patched JVM properties (`egl.displayid`, `glassplatform`, etcetera) can now be overridden by just manually specifying them.

**Comment by FDelporte** [comment]
@ppmathis nice work!!
